In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

In [4]:
print('add x, y', x + y)
print('add x, y with numpy numpy function', np.add(x,y))

add x, y [ 6.5  8.5 10.5 12.5]
add x, y with numpy numpy function [ 6.5  8.5 10.5 12.5]


In [5]:
print('subtract x, y', x - y)
print('subtract x, y with numpy numpy function', np.subtract(x,y))

subtract x, y [-4.5 -4.5 -4.5 -4.5]
subtract x, y with numpy numpy function [-4.5 -4.5 -4.5 -4.5]


#### operation on 2D array

In [6]:
m = np.array([1,2,3,4]).reshape(2,2)
n = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

In [7]:
print('add x, y', m + n)
print('add x, y with numpy numpy function', np.add(m,n))

print('\nSubtract x, y', m - n)
print('Subtract x, y with numpy numpy function', np.subtract(m,n))

print('\nMulitply x, y', m * n)
print('Multiply x, y with numpy numpy function', np.multiply(m,n))

print('\nDivide x, y', m / n)
print('Divide x, y with numpy numpy function', np.divide(m,n))

add x, y [[ 6.5  8.5]
 [10.5 12.5]]
add x, y with numpy numpy function [[ 6.5  8.5]
 [10.5 12.5]]

Subtract x, y [[-4.5 -4.5]
 [-4.5 -4.5]]
Subtract x, y with numpy numpy function [[-4.5 -4.5]
 [-4.5 -4.5]]

Mulitply x, y [[ 5.5 13. ]
 [22.5 34. ]]
Multiply x, y with numpy numpy function [[ 5.5 13. ]
 [22.5 34. ]]

Divide x, y [[0.18181818 0.30769231]
 [0.4        0.47058824]]
Divide x, y with numpy numpy function [[0.18181818 0.30769231]
 [0.4        0.47058824]]


In [11]:
print(m)
print('sqaure root', np.sqrt(m))
print('square', np.power(m, 2))
print('exponential', np.exp(m))

print('\nAverage', np.mean(m))
print('Average of all rows', np.mean(m, axis=1))
print('Average of all columns', np.mean(m, axis=0))

[[1 2]
 [3 4]]
sqaure root [[1.         1.41421356]
 [1.73205081 2.        ]]
square [[ 1  4]
 [ 9 16]]
exponential [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

Average 2.5
Average of all rows [1.5 3.5]
Average of all columns [2. 3.]


In [14]:
print(m)
print('\nMedian', np.median(m))
print('Median of all rows', np.median(m, axis=1))
print('Median of all columns', np.median(m, axis=0))

print('\nStandard Deviation', np.std(m))
print('Standard Deviation of all rows', np.std(m, axis=1))
print('Standard Deviation of all columns', np.std(m, axis=0))

print('\nSum', np.sum(m))
print('Sum of all rows', np.sum(m, axis=1))
print('Sum of all columns', np.sum(m, axis=0))

print('\nmin', np.min(m))
print('min of all rows', np.min(m, axis=1))
print('min of all columns', np.min(m, axis=0))

print('\nmax', np.max(m))
print('max of all rows', np.max(m, axis=1))
print('max of all columns', np.max(m, axis=0))

[[1 2]
 [3 4]]

Median 2.5
Median of all rows [1.5 3.5]
Median of all columns [2. 3.]

Standard Deviation 1.118033988749895
Standard Deviation of all rows [0.5 0.5]
Standard Deviation of all columns [1. 1.]

Sum 10
Sum of all rows [3 7]
Sum of all columns [4 6]

min 1
min of all rows [1 3]
min of all columns [1 2]

max 4
max of all rows [2 4]
max of all columns [3 4]


### Statistical Functions

In [23]:
print(m)
print('\nMedian', np.median(m))
print('Median of all rows', np.median(m, axis=1))
print('Median of all columns', np.median(m, axis=0))

print('\nStandard Deviation', m.std())
print('Standard Deviation of all rows', m.std(axis=1))
print('Standard Deviation of all columns', m.std(axis=0))

print('\nSum', m.sum())
print('Sum of all rows', m.sum(axis=1))
print('Sum of all columns', m.sum(axis=0))

print('\nmin', np.min(m))
print('min of all rows', m.min(axis=1))
print('min of all columns', m.min(axis=0))

print('\nmax', np.max(m))
print('max of all rows', m.max(axis=1))
print('max of all columns', m.max(axis=0))

[[1 2]
 [3 4]]

Median 2.5
Median of all rows [1.5 3.5]
Median of all columns [2. 3.]

Standard Deviation 1.118033988749895
Standard Deviation of all rows [0.5 0.5]
Standard Deviation of all columns [1. 1.]

Sum 10
Sum of all rows [3 7]
Sum of all columns [4 6]

min 1
min of all rows [1 3]
min of all columns [1 2]

max 4
max of all rows [2 4]
max of all columns [3 4]


In [24]:
q = np.array([[3,3], [4,6]])

# We print x
print()
print('q = \n', q)
print()

print('3  *q = \n', 3*  q)
print()
print('3 + q = \n', 3 + q)
print()
print('q - 3 = \n', q - 3)
print()
print('q / 3 = \n', q / 3)


q = 
 [[3 3]
 [4 6]]

3  *q = 
 [[ 9  9]
 [12 18]]

3 + q = 
 [[6 6]
 [7 9]]

q - 3 = 
 [[0 0]
 [1 3]]

q / 3 = 
 [[1.         1.        ]
 [1.33333333 2.        ]]
