In [1]:
import numpy as np

### Boolean slicing with Array

In [4]:
n = np.arange(25).reshape(5,5)
print(n)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [10]:
print('Elements of n greater than 10: ', n[(n>10)])

print('\nElements of n greater than or equal to 15: ', n[(n>=15)])

print('\nElements of n greater than 12 and less than  15: ', n[(n > 12) & (n < 15)])

Elements of n greater than 10:  [11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Elements of n greater than or equal to 15:  [15 16 17 18 19 20 21 22 23 24]

Elements of n greater than 12 and less than  15:  [13 14]


##### Use Boolean Indexing to assign value

In [13]:
n[(n > 13) & (n < 20)] = -1
print(n)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 -1]
 [-1 -1 -1 -1 -1]
 [20 21 22 23 24]]


### Set Operations

In [14]:
p = np.array([2,5,6,8,10])

q = np.array([4,6,8,10,12])

In [18]:
print('Elements that are both p and q', np.intersect1d(p,q))
print('\nElements that are not in p and q', np.setdiff1d(p,q))
print('\nAll Elements of both p and q', np.union1d(p,q)) 

Elements that are both p and q [ 6  8 10]

Elements that are not in p and q [2 5]

All Elements of both p and q [ 2  4  5  6  8 10 12]


#### Sort Operation

In [20]:
c = np.random.randint(1,20, size=10)
print(c)

[ 3 10  5  7 11 12  7 17  1  3]


In [21]:
print(np.sort(c))

[ 1  3  3  5  7  7 10 11 12 17]


In [25]:
d = c[2:7]
print(d)
d.sort()
print(d)

[ 5  7  7 11 12]
[ 5  7  7 11 12]
