### numpy Araay Operation

In [4]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print('first element: ', x[0])
print('second element: ', x[1])
print('last element: ', x[-1])
print('fifth element to last: ', x[-5])

first element:  1
second element:  2
last element:  5
fifth element to last:  1


In [5]:
# modify the 4th element
x[3] = 15

In [6]:
print(x)

[ 1  2  3 15  5]


#### Access Elements 2 Dimensional Array

In [65]:
y = np.array([[1,2,4], [4,2,3], [5,2,3], [5,6,8]])

In [66]:
print(y)
print('first element in list_1 (0,0): ', y[0,0])
print('second element in list_1 (0,1): ', y[0,1])
print('first element in list_2 (1,0): ', y[1, 0])
print('second element in list_2 (1,1): ', y[1,1])
print('first element in last list (-1, 0): ', y[-1,0])
print('last element in last list (-1,-1): ', y[-1,-1])

[[1 2 4]
 [4 2 3]
 [5 2 3]
 [5 6 8]]
first element in list_1 (0,0):  1
second element in list_1 (0,1):  2
first element in list_2 (1,0):  4
second element in list_2 (1,1):  2
first element in last list (-1, 0):  5
last element in last list (-1,-1):  8


#### Moddify Elements in 2 Dimensional Array

In [67]:
y[0,0] = 10
print(y)

[[10  2  4]
 [ 4  2  3]
 [ 5  2  3]
 [ 5  6  8]]


#### Use delete() for delete element in 2 Dimensional Array

In [41]:
y = np.delete(y, [0,1])
print('Deleted the second and third array', y)

Deleted the second and third array [4 4 2 3 5 2 3 5 6 8]


In [59]:
y = np.delete(y, [0,1], axis=0)
print('deletes the first and second row: ', y)

deletes the first and second row:  [[5 2 3]
 [5 6 8]]


In [63]:
y = np.delete(y, 0, axis=1)
print('deletes the first column', y)

deletes the first column [[2 4]
 [2 3]
 [2 3]
 [6 8]]


In [68]:
# We append a new row containing 7,8,9 to y
y = np.append(y, [[7,8,9]], axis=0)
print(y)

[[10  2  4]
 [ 4  2  3]
 [ 5  2  3]
 [ 5  6  8]
 [ 7  8  9]]


In [ ]:
# We insert a row between the first and last row of y
w = np.insert(y,1,[4,5,6],axis=0)

In [ ]:
# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))


#### Slicing 2D Array Operations

In [69]:
o = np.arange(20).reshape(4,5)
print(o)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [70]:
selected_rows = o[1:4,2:5]
print(selected_rows)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [72]:
same_as_selected_row = o[1:,2:5]
print(same_as_selected_row)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [80]:
third_row_2_4_column = o[:3,2:5]
print(third_row_2_4_column)
print('Third row', o[2,:])
print('Third column', o[:,2])
print('Third column with rank2 array', o[:,2:3])

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
Third row [10 11 12 13 14]
Third column [ 2  7 12 17]
Third column with rank2 array [[ 2]
 [ 7]
 [12]
 [17]]


### Array modification
An array created from an array is a copy/view of the original array, which means any modification will reflect on either copy

In [82]:
st = np.arange(30).reshape(5,6)
print(st)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [83]:
sq = st[1:3,3:5]
print(sq)

[[ 9 10]
 [15 16]]


In [90]:
sq[1,0] = 512

print('modifying a copy modifies st', st)
print('modifying sq modifies the st', sq)

modifying a copy modifies st [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14 512  16  17]
 [ 18  19  20  21  22  23]
 [ 24  25  26  27  28  29]]
modifying sq modifies the st [[  9  10]
 [512  16]]


#### Copy - with copy the underlying array is not modified

In [93]:
sq_copy = np.copy(st[2:,3:])
print(sq_copy)
print(st)

[[512  16  17]
 [ 21  22  23]
 [ 27  28  29]]
[[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14 512  16  17]
 [ 18  19  20  21  22  23]
 [ 24  25  26  27  28  29]]


In [95]:
sq_copy[2,0] = 600
print(sq_copy)
print(st)

[[512  16  17]
 [ 21  22  23]
 [600  28  29]]
[[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14 512  16  17]
 [ 18  19  20  21  22  23]
 [ 24  25  26  27  28  29]]


#### Indices - using array to create indices

In [98]:
indices = np.array([1,2])
print(indices)

[1 2]


In [103]:
slice_with_indices = st[indices,:]
same_as = st[1:3,:]
print(slice_with_indices)
print(same_as)

[[  6   7   8   9  10  11]
 [ 12  13  14 512  16  17]]
[[  6   7   8   9  10  11]
 [ 12  13  14 512  16  17]]


#### Use an array as indices to extract specific rows from a rank 2 ndarray

In [115]:
extract_with_indices = np.random.randint(1,20, size=(50,5))
print(extract_with_indices)
print(extract_with_indices.shape)

[[16  5 12  2 14]
 [ 1 17 14 18  6]
 [ 6 15 19 14  8]
 [13 19  4 15  9]
 [ 2  3 15  4  8]
 [18 16  5  1  5]
 [ 5 18  7  3  4]
 [ 7  7 11 13  1]
 [12  7  7 12 12]
 [ 3  9  7  9  3]
 [13  8  4  2 10]
 [ 2  2 16  7  7]
 [ 6  5  9  4 10]
 [17  5  2 12 17]
 [ 9  2 15  8 16]
 [ 1 13 19 16 15]
 [ 3 17 16  8 12]
 [ 1  6  8 16 15]
 [10 15  4  8 14]
 [19  5 19  9  1]
 [ 2 13 11 15  4]
 [ 8  5 18 19  2]
 [ 2  1  7  6  1]
 [13 14 19  5 18]
 [ 6 15  1 12 12]
 [11 19 16  9  8]
 [ 7  4 18 13 12]
 [ 1 11  4  6 10]
 [16 15  1  5 19]
 [10 13 17  7  6]
 [ 8 16  3 10 12]
 [ 2  8  4 18  8]
 [ 9 18  3 10  2]
 [17 10  8 10  3]
 [ 1 19  1  2 16]
 [19 19  8 18 10]
 [10 18 13 13  4]
 [17 13  1 14 19]
 [10 17 17  5  9]
 [ 5 16 13  8 11]
 [16  9  2 12 10]
 [18  1 11 19 19]
 [ 9  1 17 12 12]
 [15  3 19 13  8]
 [17  9  2  7  9]
 [ 9  2 17  1 18]
 [18 18 10  8 17]
 [ 6 14 19 12  5]
 [11 12 17  2 12]
 [18 19  3 17 14]]
(50, 5)


In [109]:
# Create a rank 1 ndarray that contains a randomly chosen 10 values between `0` to `len(X)` (50)
# The row_indices would represent the indices of rows of X
row_indices = np.random.randint(0,50, size=10)
print("Random 10 indices are: ", row_indices)

Random 10 indices are:  [29 32 35 49 42 21 27 21  6 34]


In [122]:
print(extract_with_indices[row_indices, :])
print()
print(extract_with_indices[row_indices[4:5], :])

[[10 13 17  7  6]
 [ 9 18  3 10  2]
 [19 19  8 18 10]
 [18 19  3 17 14]
 [ 9  1 17 12 12]
 [ 8  5 18 19  2]
 [ 1 11  4  6 10]
 [ 8  5 18 19  2]
 [ 5 18  7  3  4]
 [ 1 19  1  2 16]]

[[ 9  1 17 12 12]]


#### Unique function returns unique elements in an array


In [127]:
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
print(X)

unique_elements_X = np.unique(X)
print('unique elements of x', unique_elements_X)

[[1 2 3]
 [5 2 8]
 [1 2 3]]
unique elements of x [1 2 3 5 8]
