# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [2]:
# import NumPy into Python
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0, 5001, size=(1000, 20))

# print the shape of X
print(X)

[[4888 2651 2247 ...  491  150 3110]
 [4552  179 3706 ... 3452 4639 4535]
 [1350 4821 2414 ... 3425 4469 3354]
 ...
 [1184 1068 1946 ...  153 2394 4532]
 [2074   23 4897 ... 2850 2214 4949]
 [ 403 3431 3347 ... 1189 4908   14]]


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [3]:
# Average of the values in each column of X
ave_cols = X.mean(axis=0)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis=0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [4]:
# Print the shape of ave_cols
print(ave_cols)

# Print the shape of std_cols
print(std_cols)

[2504.165 2452.706 2474.369 2621.559 2480.007 2458.726 2556.986 2512.582
 2581.307 2474.974 2474.909 2563.666 2557.285 2568.875 2483.429 2488.22
 2329.733 2473.516 2451.533 2549.951]
[1465.60025033 1465.90465159 1413.29128096 1417.30865605 1425.73318856
 1476.9938913  1476.96944376 1448.84657203 1459.93402548 1458.37277516
 1446.01381484 1427.2462452  1443.75730917 1418.15285825 1431.25009029
 1427.95509859 1443.83934553 1436.460117   1473.18139172 1456.01872811]


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [5]:
# Mean normalize X
X_norm = (X - ave_cols) / std_cols

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [8]:
# Print the average of all the values of X_norm
print(X_norm.mean())

# Print the average of the minimum value in each column of X_norm
print(np.min(X_norm, axis=0).mean())

# Print the average of the maximum value in each column of X_norm
print(np.max(X_norm, axis=0).mean())

-1.8474111129762604e-17
-1.7286289086183426
1.72297530767031


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [9]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([3, 2, 4, 1, 0])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [24]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(X_norm.shape[0])


Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [22]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.

sixty_per = int(len(X_norm) * 0.6 )

# lets get the next 20% which 20 + 60 = 80%; 800 lines
eighty_per = int(len(X_norm) * 0.8 )

# Create a Training Set
X_train = X_norm[row_indices[:sixty_per], :]

# Create a Cross Validation Set
X_crossVal = X_norm[row_indices[sixty_per:eighty_per], :]

# Create a Test Set
X_test = X_norm[row_indices[eighty_per: ], :]

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [21]:
# Print the shape of X_train
print(X_train)

# Print the shape of X_crossVal
print(X_crossVal)

# Print the shape of X_test
print(X_test)

[[ 0.42906311  0.42110106  0.60187946 ... -0.58164929 -1.55006913
   1.08655814]
 [-0.87279256  0.65235757 -1.36799047 ...  0.93666645  0.23518285
   0.78161701]
 [-1.33608397  1.15580096  1.62714582 ...  1.54997969  0.17748459
   0.66623388]
 ...
 [ 1.62311312  1.65310479  1.07170476 ... -0.15560195 -1.46114593
  -0.85709818]
 [-0.35969221 -0.19148994 -0.56843838 ... -0.25306376  1.27646671
   0.22530548]
 [-0.1679619  -0.63421997  0.17521583 ...  1.17892866  0.21617637
   0.34274903]]
[[ 7.22127333e-02 -8.77997078e-02  1.09222424e+00 ...  6.52634897e-01
   1.67460709e-03  5.13763309e-01]
 [ 1.65245264e+00 -5.40762320e-01  1.31015526e+00 ... -6.37093915e-02
  -9.81094391e-02  1.58380449e+00]
 [-1.07748685e+00 -1.90125599e-01  1.29954173e+00 ... -1.61404829e+00
  -2.69846607e-01 -6.66853373e-01]
 ...
 [ 8.08429856e-01  1.72882595e+00  1.70780860e+00 ...  8.50343136e-01
   8.26420295e-01 -5.03393937e-01]
 [ 5.87360025e-01  1.56987973e+00 -1.35100883e+00 ... -2.16167505e-01
  -1.56975442