In [5]:
import numpy as np

In [6]:
x = np.array([1,3,4,6,7])

In [8]:
print('x: ', x)

x:  [1 3 4 6 7]


In [9]:
x.ndim

1

In [10]:
y = np.array([[1,2,3], [2,3,4], [4,5,6]])

In [12]:
y.ndim

2

In [14]:
y.shape

(3, 3)

In [17]:
print('x:', x)
print(x.ndim)
print('x has dimensions:', x.shape)
print('The elements in x are of type:', x.dtype)
print('x is an object of type:',type(x))

x: [1 3 4 6 7]
1
x has dimensions: (5,)
The elements in x are of type: int64
x is an object of type: <class 'numpy.ndarray'>


In [ ]:
## Save the numpy array to a file
x.save('testing_numpy', x)

## saved that as testing_numpy.npy

In [18]:
## load the saved arrary from a file
y = np.load('testing_numpy.npy')

## Builtin Functions

## Builtin Functions with Zeros arrays

In [20]:
z = np.zeros((4,3))

In [21]:
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Builtin Funtion with one arrays


In [25]:
q = np.ones((3,2), dtype=int)

In [26]:
print(q)

[[1 1]
 [1 1]
 [1 1]]


### Builtin Function with Constant

In [27]:
t = np.full((4,2), 5)

In [28]:
print(t)

[[5 5]
 [5 5]
 [5 5]
 [5 5]]


### Builtin Functions with Identity Matrix

In [33]:
k = np.eye(4)

In [34]:
print(k)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Builtin Function with Diagonal Constants

In [36]:
w = np.diag((10, 20, 30, 40, 50, 60, 70))

In [37]:
print(w)

[[10  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0]
 [ 0  0 30  0  0  0  0]
 [ 0  0  0 40  0  0  0]
 [ 0  0  0  0 50  0  0]
 [ 0  0  0  0  0 60  0]
 [ 0  0  0  0  0  0 70]]


In [59]:
qu = np.arange(10).reshape(2,5)
print(qu)
wq = np.diag(qu, k=2)
print(wq)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[2 8]


### Builtin Functions with arange

In [40]:
wq = np.arange(10)

In [41]:
print(wq)

[0 1 2 3 4 5 6 7 8 9]


```
linspace is a Better alternative to arange in the case of floating types
usage
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
```

In [43]:
v = np.linspace(0,25,10)
print(v)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


`exluding the stop point use the endpoint = False`

In [45]:
vs = np.linspace(0,25,10, endpoint = False)
print(vs)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


The np.reshape(ndarray, new_shape) function converts the given ndarray into the specified new_shape. It is important to note that the new_shape should be compatible with the number of elements in the given ndarray.

In [46]:
new_shape = np.reshape(vs, (2,5))
print(new_shape)

[[ 0.   2.5  5.   7.5 10. ]
 [12.5 15.  17.5 20.  22.5]]


reshape() is a method, thus it can be called directly

In [48]:
wv = np.linspace(0,25,10, endpoint=False).reshape(2,5)
print(wv)

[[ 0.   2.5  5.   7.5 10. ]
 [12.5 15.  17.5 20.  22.5]]


In [50]:
rd = np.random.random((3,3))
print(rd)

[[0.04358549 0.533292   0.56096735]
 [0.86033383 0.53475904 0.67252971]
 [0.76513164 0.44781183 0.30085988]]


In [52]:
rint = np.random.randint(4,15,size=(3,2))
print(rint)

[[10  9]
 [12 11]
 [ 9  5]]


#### Create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
#### with a mean of zero and a standard deviation of 0.1.


In [55]:
gaussian_distribution = np.random.normal(0, 0.1, size=(1000,1000))
print(gaussian_distribution)

[[ 0.01736314 -0.00830315  0.03081162 ...  0.04975056  0.11645275
  -0.04733188]
 [-0.1203566   0.00143787  0.12319287 ... -0.05351866 -0.14923508
   0.16887914]
 [-0.03848632 -0.09264253  0.07190005 ...  0.25501415 -0.07118779
  -0.02644779]
 ...
 [ 0.02555528  0.11562878  0.08323948 ...  0.08886563  0.0346453
  -0.00665802]
 [-0.092116   -0.18439858 -0.02018909 ...  0.0260747   0.14760965
  -0.05287955]
 [-0.12832417  0.14719308  0.09527483 ...  0.21710586  0.13411832
   0.11334109]]
